export const FETCH_PRODUCTS_BEGINN = "FETCH_PRODUCTS_BEGINN"
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"





export const FETCH_DEVICES_BEGINN = "FETCH_DEVICES_BEGINN"
export const FETCH_DEVICES_FAIL = "FETCH_DEVICES_FAIL"
export const FETCH_DEVICES_SUCCESS = "FETCH_DEVICES_SUCCESS"
export const FETCH_DEVICES = "FETCH_DEVICES"


